---
- name: Copy AMADUPL load lib
  hosts: zos_host
  gather_facts: false
  environment: "{{ environment_vars }}"
  tasks:

    - name: Copy AMAPDUPL member from ZOS31T.SYS1.MIGLIB to SYS1.MIGLIB
      ibm.ibm_zos_core.zos_copy:
        src: ZOS31T.SYS1.MIGLIB(AMAPDUPL)
        dest: SYS1.MIGLIB(AMAPDUPL)
        remote_src: true
        executable: true
        force_lock: true
        force: true
        
