---
- name: List exisiting software instances
  hosts: zos_host
  gather_facts: false
  environment: "{{ environment_vars }}"
  vars:
    #zmf_host: itzvsi-zos-pejjzea.techzone.ibm.com
    zmf_host: "{{ ansible_host }}"
    zmf_port: 10443
    zmf_user: IBMUSER
    zmf_password: "w6AF73xLy*"
    #password:

  tasks:

   # - ansible.builtin.set_fact:
   #     zos_passphrase: "{% raw %}'{{ password }}'{% endraw %}"


    #- name: Print json data to terminal for visual verification.
    #  ansible.builtin.debug:
    #    msg: '{% raw %}'{{ password }}'{% endraw %}'
    
    - name: Print json data to terminal for visual verification.
      ansible.builtin.debug:
        msg: '{{ '{{' }} password {{ '}}' }}'

        
